/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.Reporte;

import Interfaces.MenuPrincipal;
import Variables.Consulta.VacunaConsulta;
import Variables.Modelo.ModeloUsuario;
import Variables.Modelo.ModeloVacuna;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class ReporteVacunacion extends javax.swing.JFrame {

    private ModeloVacuna modeloVacuna;
    private ModeloUsuario modeloUsuario;

    /**
     * Creates new form ReporteVacunacion
     */
    public ReporteVacunacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modeloVacuna = new ModeloVacuna();
        this.modeloUsuario = new ModeloUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_toolbar_menu = new javax.swing.JPanel();
        lb_titulo_registro = new javax.swing.JLabel();
        panel_consulta_usuario = new javax.swing.JPanel();
        tabla_usuario = new javax.swing.JScrollPane();
        jtable_reporte = new javax.swing.JTable();
        txt_buscar_identificacion = new javax.swing.JTextField();
        lb_identificacion = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_toolbar_menu.setBackground(new java.awt.Color(0, 102, 102));
        panel_toolbar_menu.setPreferredSize(new java.awt.Dimension(984, 50));
        panel_toolbar_menu.setRequestFocusEnabled(false);

        lb_titulo_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_titulo_registro.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_registro.setText("REPORTE - HOSPITAL COMUNAL LAS MERCEDES");
        lb_titulo_registro.setToolTipText("");

        javax.swing.GroupLayout panel_toolbar_menuLayout = new javax.swing.GroupLayout(panel_toolbar_menu);
        panel_toolbar_menu.setLayout(panel_toolbar_menuLayout);
        panel_toolbar_menuLayout.setHorizontalGroup(
            panel_toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_titulo_registro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_toolbar_menuLayout.setVerticalGroup(
            panel_toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_titulo_registro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtable_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Identificación", "Vacuna", "Dosis", "Fecha Vacunación", "Próxima Dosis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_usuario.setViewportView(jtable_reporte);

        lb_identificacion.setText("Identificación");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_consulta_usuarioLayout = new javax.swing.GroupLayout(panel_consulta_usuario);
        panel_consulta_usuario.setLayout(panel_consulta_usuarioLayout);
        panel_consulta_usuarioLayout.setHorizontalGroup(
            panel_consulta_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_consulta_usuarioLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panel_consulta_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabla_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_consulta_usuarioLayout.createSequentialGroup()
                        .addComponent(lb_identificacion)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscar_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        panel_consulta_usuarioLayout.setVerticalGroup(
            panel_consulta_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_consulta_usuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_consulta_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_identificacion)
                    .addComponent(btn_buscar))
                .addGap(27, 27, 27)
                .addComponent(tabla_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_consulta_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_toolbar_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_toolbar_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_consulta_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        try {
            if (TextoVacio(txt_buscar_identificacion.getText())) {
                JOptionPane.showMessageDialog(null, "Diligencie una identificación para buscar");
            } else {
                int idPersona;

                idPersona = this.modeloUsuario.RecuperarIdPersona(txt_buscar_identificacion.getText());

                if (idPersona != 0) {
                    DefaultTableModel modelo = new DefaultTableModel();
                    jtable_reporte.setModel(modelo);
                    modelo.addColumn("Id");
                    modelo.addColumn("Identificación");
                    modelo.addColumn("Vacuna");
                    modelo.addColumn("Dosis");
                    modelo.addColumn("Fecha Vacunación");
                    modelo.addColumn("Próxima Dosis");

                    ArrayList<VacunaConsulta> listaVacuna = this.modeloVacuna.ObtenerReporteVacunacion(idPersona);

                    if (listaVacuna.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron registros");
                    } else {
                        for (int i = 0; i < listaVacuna.size(); i++) {
                            Object[] datosRegistro = {
                                listaVacuna.get(i).getId(),
                                listaVacuna.get(i).getIdentificacion(),
                                listaVacuna.get(i).getVacuna(),
                                listaVacuna.get(i).getDosis(),
                                listaVacuna.get(i).getFechaVacunacion(),
                                listaVacuna.get(i).getProximaFecha()
                            };
                            modelo.addRow(datosRegistro);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La identificación ingresada no se encuentra registrada en el sistema");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReporteVacunacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteVacunacion().setVisible(true);
            }
        });
    }

    private static boolean TextoVacio(String parametro) {
        return parametro == null || parametro.trim().length() == 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JTable jtable_reporte;
    private javax.swing.JLabel lb_identificacion;
    private javax.swing.JLabel lb_titulo_registro;
    private javax.swing.JPanel panel_consulta_usuario;
    private javax.swing.JPanel panel_toolbar_menu;
    private javax.swing.JScrollPane tabla_usuario;
    private javax.swing.JTextField txt_buscar_identificacion;
    // End of variables declaration//GEN-END:variables
}
