/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces.Vacuna;

import Interfaces.MenuPrincipal;
import Variables.Entidad.Dosis;
import Variables.Entidad.RegistroVacuna;
import Variables.Entidad.Vacuna;
import Variables.Modelo.ModeloDosis;
import Variables.Modelo.ModeloUsuario;
import Variables.Modelo.ModeloVacuna;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class RegistroVacunacion extends javax.swing.JFrame {

    private ModeloUsuario modeloUsuario;
    private ModeloVacuna modeloVacuna;
    private ModeloDosis modeloDosis;

    /**
     * Creates new form RegistroVacunacion
     */
    public RegistroVacunacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.modeloUsuario = new ModeloUsuario();
        this.modeloVacuna = new ModeloVacuna();
        this.modeloDosis = new ModeloDosis();
        CargarListaVacuna();
        CargarListaDosis();
    }

    private void CargarListaVacuna() {
        ArrayList<Vacuna> listaVacuna = this.modeloVacuna.ObtenerListaVacuna();
        cb_vacuna.removeAllItems();
        cb_vacuna.addItem("Seleccione una opción");
        for (int i = 0; i < listaVacuna.size(); i++) {
            cb_vacuna.addItem(listaVacuna.get(i).getDescripcion());
        }
    }

    private void CargarListaDosis() {
        ArrayList<Dosis> listaDosis = this.modeloDosis.ObtenerListaDosis();
        cb_dosis.removeAllItems();
        cb_dosis.addItem("Seleccione una opción");
        for (int i = 0; i < listaDosis.size(); i++) {
            cb_dosis.addItem(listaDosis.get(i).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_toolbar_menu = new javax.swing.JPanel();
        lb_titulo_registro = new javax.swing.JLabel();
        panel_registro = new javax.swing.JPanel();
        lb_identificacion = new javax.swing.JLabel();
        lb_vacuna = new javax.swing.JLabel();
        lb_fecha_proxima_dosis = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        txt_identificacion = new javax.swing.JTextField();
        ftf_fecha_proxima_dosis = new javax.swing.JFormattedTextField();
        cb_vacuna = new javax.swing.JComboBox<>();
        lb_dosis = new javax.swing.JLabel();
        cb_dosis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_toolbar_menu.setBackground(new java.awt.Color(0, 102, 102));
        panel_toolbar_menu.setPreferredSize(new java.awt.Dimension(984, 50));
        panel_toolbar_menu.setRequestFocusEnabled(false);

        lb_titulo_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_titulo_registro.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_registro.setText("VACUNA - HOSPITAL COMUNAL LAS MERCEDES");
        lb_titulo_registro.setToolTipText("");

        javax.swing.GroupLayout panel_toolbar_menuLayout = new javax.swing.GroupLayout(panel_toolbar_menu);
        panel_toolbar_menu.setLayout(panel_toolbar_menuLayout);
        panel_toolbar_menuLayout.setHorizontalGroup(
            panel_toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_titulo_registro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_toolbar_menuLayout.setVerticalGroup(
            panel_toolbar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_titulo_registro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lb_identificacion.setText("Identificación:");

        lb_vacuna.setText("Vacuna:");

        lb_fecha_proxima_dosis.setText("Fecha próxima dosis:");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        ftf_fecha_proxima_dosis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        ftf_fecha_proxima_dosis.setToolTipText("yyyy-MM-dd");

        lb_dosis.setText("Dosis:");

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_registroLayout.createSequentialGroup()
                        .addComponent(lb_fecha_proxima_dosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftf_fecha_proxima_dosis))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_registroLayout.createSequentialGroup()
                        .addComponent(lb_identificacion)
                        .addGap(12, 12, 12)
                        .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(lb_vacuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_vacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(lb_dosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_dosis, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_vacuna)
                    .addComponent(cb_vacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dosis)
                    .addComponent(cb_dosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_guardar)
                .addGap(42, 42, 42)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_fecha_proxima_dosis)
                    .addComponent(ftf_fecha_proxima_dosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_toolbar_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_toolbar_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        SalirDeLaPantalla();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            if (ValidarFormulario()) {
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date date = new Date(System.currentTimeMillis());              

                int idPersona = this.modeloUsuario.RecuperarIdPersona(txt_identificacion.getText());

                if (idPersona != 0) {
                    RegistroVacuna registro = new RegistroVacuna(
                            idPersona,
                            cb_vacuna.getSelectedIndex(),
                            cb_dosis.getSelectedIndex(),
                            Date.valueOf(formatter.format(date)),
                            Date.valueOf(ftf_fecha_proxima_dosis.getText())
                    );

                    try {
                        int r = this.modeloVacuna.GuardarReporteVacunacion(registro);

                        if (r != 0) {
                            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Datos almacenados correctamente", "Ok!", JOptionPane.DEFAULT_OPTION);
                            if (showConfirmDialog == 0) {
                                SalirDeLaPantalla();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al almacenar el registro");
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(RegistroVacunacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El número de identificación ingresado no se encuentra registrado en plataforma");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroVacunacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void SalirDeLaPantalla() {
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }

    private Boolean ValidarFormulario() {

        if (TextoVacio(txt_identificacion.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese la identificación del paciente");

            return false;
        }

        if (cb_vacuna.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una vacuna");
            return false;
        }

        if (cb_dosis.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una dosis");
            return false;
        }

        if (FechaVacia(ftf_fecha_proxima_dosis.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese la fecha de la siguiente dosis");
            return false;
        }

        return true;
    }

    private Boolean FechaVacia(String fecha) {
        return TextoVacio(fecha);
    }

    private static boolean TextoVacio(String parametro) {
        return parametro == null || parametro.trim().length() == 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVacunacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cb_dosis;
    private javax.swing.JComboBox<String> cb_vacuna;
    private javax.swing.JFormattedTextField ftf_fecha_proxima_dosis;
    private javax.swing.JLabel lb_dosis;
    private javax.swing.JLabel lb_fecha_proxima_dosis;
    private javax.swing.JLabel lb_identificacion;
    private javax.swing.JLabel lb_titulo_registro;
    private javax.swing.JLabel lb_vacuna;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JPanel panel_toolbar_menu;
    private javax.swing.JTextField txt_identificacion;
    // End of variables declaration//GEN-END:variables
}
