/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Alex
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_toolbar_registro = new javax.swing.JPanel();
        lb_titulo_registro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_vacunacion = new javax.swing.JToggleButton();
        btn_editar_usuario = new javax.swing.JToggleButton();
        btn_salir = new javax.swing.JToggleButton();
        btn_reporte = new javax.swing.JToggleButton();

        panel_toolbar_registro.setBackground(new java.awt.Color(0, 102, 102));
        panel_toolbar_registro.setPreferredSize(new java.awt.Dimension(984, 50));
        panel_toolbar_registro.setRequestFocusEnabled(false);

        lb_titulo_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_titulo_registro.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_registro.setText("MENU - HOSPITAL COMUNAL LAS MERCEDES");
        lb_titulo_registro.setToolTipText("");

        javax.swing.GroupLayout panel_toolbar_registroLayout = new javax.swing.GroupLayout(panel_toolbar_registro);
        panel_toolbar_registro.setLayout(panel_toolbar_registroLayout);
        panel_toolbar_registroLayout.setHorizontalGroup(
            panel_toolbar_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_registroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_titulo_registro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_toolbar_registroLayout.setVerticalGroup(
            panel_toolbar_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_registroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_titulo_registro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_vacunacion.setIcon(new javax.swing.ImageIcon("G:\\SevenCrows\\Universidad\\2022\\Periodo1\\Programacion\\Actividad3\\ProyectoB\\img\\vacuna_1.png")); // NOI18N
        btn_vacunacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vacunacionActionPerformed(evt);
            }
        });

        btn_editar_usuario.setIcon(new javax.swing.ImageIcon("G:\\SevenCrows\\Universidad\\2022\\Periodo1\\Programacion\\Actividad3\\ProyectoB\\img\\editar.png")); // NOI18N

        btn_salir.setIcon(new javax.swing.ImageIcon("G:\\SevenCrows\\Universidad\\2022\\Periodo1\\Programacion\\Actividad3\\ProyectoB\\img\\salir.png")); // NOI18N

        btn_reporte.setIcon(new javax.swing.ImageIcon("G:\\SevenCrows\\Universidad\\2022\\Periodo1\\Programacion\\Actividad3\\ProyectoB\\img\\registro.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_vacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_vacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_toolbar_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_toolbar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vacunacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vacunacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vacunacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_editar_usuario;
    private javax.swing.JToggleButton btn_reporte;
    private javax.swing.JToggleButton btn_salir;
    private javax.swing.JToggleButton btn_vacunacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_titulo_registro;
    private javax.swing.JPanel panel_toolbar_registro;
    // End of variables declaration//GEN-END:variables
}
