/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Variables.Entidad.Dosis;
import Variables.Entidad.Genero;
import Variables.Entidad.TipoIdentificacion;
import Variables.Entidad.TipoUsuario;
import Variables.Modelo.ModeloDosis;
import Variables.Modelo.ModeloGenero;
import Variables.Modelo.ModeloTipoIdentificacion;
import Variables.Modelo.ModeloTipoUsuario;
import java.util.ArrayList;

/**
 *
 * @author Alex
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargarListaGenero();
        CargarListaTipoIdentificacion();
        CargarListaTipoUsuario();
    }

    private void CargarListaGenero() {
        ModeloGenero modeloGenero = new ModeloGenero();
        ArrayList<Genero> listaGenero = modeloGenero.ObtenerListaGeneros();
        cb_genero.removeAllItems();
        cb_genero.addItem("Seleccione una opción");
        for (int i = 0; i < listaGenero.size(); i++) {
            cb_genero.addItem(listaGenero.get(i).getDescripcion());
        }
    }

    private void CargarListaTipoIdentificacion() {
        ModeloTipoIdentificacion modeloTipoIdentificacion = new ModeloTipoIdentificacion();
        ArrayList<TipoIdentificacion> listaTipoIdentificacion = modeloTipoIdentificacion.ObtenerListaTipoIdentificacion();
        cb_tipo_identificacion.removeAllItems();
        cb_tipo_identificacion.addItem("Seleccione una opción");
        for (int i = 0; i < listaTipoIdentificacion.size(); i++) {
            cb_tipo_identificacion.addItem(listaTipoIdentificacion.get(i).getDescripcion());
        }
    }

    private void CargarListaTipoUsuario() {
        ModeloTipoUsuario modeloTipoUsuario = new ModeloTipoUsuario();
        ArrayList<TipoUsuario> listaTipoUsuario = modeloTipoUsuario.ObtenerListaTipoUsuario();
        cb_tipo_usuario.removeAllItems();
        cb_tipo_usuario.addItem("Seleccione una opción");
        for (int i = 0; i < listaTipoUsuario.size(); i++) {
            cb_tipo_usuario.addItem(listaTipoUsuario.get(i).getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_toolbar_registro = new javax.swing.JPanel();
        lb_titulo_registro = new javax.swing.JLabel();
        panel_registro = new javax.swing.JPanel();
        lb_tipo_identificacion = new javax.swing.JLabel();
        lb_identificacion = new javax.swing.JLabel();
        lb_primer_nombre = new javax.swing.JLabel();
        lb_segundo_nombre = new javax.swing.JLabel();
        lb_primer_apellido = new javax.swing.JLabel();
        lb_segundo_apellido = new javax.swing.JLabel();
        lb_genero = new javax.swing.JLabel();
        lb_fecha_nacimiento = new javax.swing.JLabel();
        lb_tipo_usuario = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        cb_tipo_identificacion = new javax.swing.JComboBox<>();
        cb_tipo_usuario = new javax.swing.JComboBox<>();
        txt_identificacion = new javax.swing.JTextField();
        txt_primer_nombre = new javax.swing.JTextField();
        txt_segundo_nombre = new javax.swing.JTextField();
        txt_primer_apellido = new javax.swing.JTextField();
        ftf_fecha_nacimiento = new javax.swing.JFormattedTextField();
        cb_genero = new javax.swing.JComboBox<>();
        txt_segundo_apellido = new javax.swing.JTextField();
        lb_tipo_usuario1 = new javax.swing.JLabel();
        cb_activo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_toolbar_registro.setBackground(new java.awt.Color(0, 102, 102));
        panel_toolbar_registro.setPreferredSize(new java.awt.Dimension(984, 50));
        panel_toolbar_registro.setRequestFocusEnabled(false);

        lb_titulo_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_titulo_registro.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo_registro.setText("REGISTRO - HOSPITAL COMUNAL LAS MERCEDES");
        lb_titulo_registro.setToolTipText("");

        javax.swing.GroupLayout panel_toolbar_registroLayout = new javax.swing.GroupLayout(panel_toolbar_registro);
        panel_toolbar_registro.setLayout(panel_toolbar_registroLayout);
        panel_toolbar_registroLayout.setHorizontalGroup(
            panel_toolbar_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_registroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_titulo_registro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_toolbar_registroLayout.setVerticalGroup(
            panel_toolbar_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_toolbar_registroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_titulo_registro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lb_tipo_identificacion.setText("Tipo de identificación:");

        lb_identificacion.setText("Identificación:");

        lb_primer_nombre.setText("Primer nombre:");

        lb_segundo_nombre.setText("Segundo nombre:");

        lb_primer_apellido.setText("Primer apellido:");

        lb_segundo_apellido.setText("Segundo apellido:");

        lb_genero.setText("Genero:");

        lb_fecha_nacimiento.setText("Fecha de nacimiento:");

        lb_tipo_usuario.setText("Tipo de usuario:");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        ftf_fecha_nacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        lb_tipo_usuario1.setText("Activo:");

        cb_activo.setSelected(true);

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tipo_usuario)
                    .addComponent(lb_fecha_nacimiento)
                    .addComponent(lb_genero)
                    .addComponent(lb_segundo_apellido)
                    .addComponent(lb_primer_apellido)
                    .addComponent(lb_segundo_nombre)
                    .addComponent(lb_primer_nombre)
                    .addComponent(lb_identificacion)
                    .addComponent(lb_tipo_identificacion)
                    .addComponent(lb_tipo_usuario1))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_activo)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_primer_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_segundo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftf_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipo_identificacion)
                    .addComponent(cb_tipo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_primer_nombre)
                    .addComponent(txt_primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_segundo_nombre)
                    .addComponent(txt_segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_primer_apellido)
                    .addComponent(txt_primer_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_segundo_apellido)
                    .addComponent(txt_segundo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_genero)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_fecha_nacimiento)
                    .addComponent(ftf_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipo_usuario)
                    .addComponent(cb_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_activo)
                    .addComponent(lb_tipo_usuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_regresar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_toolbar_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_toolbar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Ingreso ingreso = new Ingreso();
        ingreso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JCheckBox cb_activo;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_tipo_identificacion;
    private javax.swing.JComboBox<String> cb_tipo_usuario;
    private javax.swing.JFormattedTextField ftf_fecha_nacimiento;
    private javax.swing.JLabel lb_fecha_nacimiento;
    private javax.swing.JLabel lb_genero;
    private javax.swing.JLabel lb_identificacion;
    private javax.swing.JLabel lb_primer_apellido;
    private javax.swing.JLabel lb_primer_nombre;
    private javax.swing.JLabel lb_segundo_apellido;
    private javax.swing.JLabel lb_segundo_nombre;
    private javax.swing.JLabel lb_tipo_identificacion;
    private javax.swing.JLabel lb_tipo_usuario;
    private javax.swing.JLabel lb_tipo_usuario1;
    private javax.swing.JLabel lb_titulo_registro;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JPanel panel_toolbar_registro;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_primer_apellido;
    private javax.swing.JTextField txt_primer_nombre;
    private javax.swing.JTextField txt_segundo_apellido;
    private javax.swing.JTextField txt_segundo_nombre;
    // End of variables declaration//GEN-END:variables
}
